13.0 Add CAByS Code
odoocr/l10n_cr pull request #217
Opened 2020-12-01 23:40 UTC by TheCloneMaster

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

2020-12-02 03:32 UTC, randall-vx commented on cr_electronic_invoice/models/account_move.py
> +                            #elif inv_line.product_id.categ_id and inv_line.product_id.categ_id.cabys_code:
Remove commented lines

2020-12-02 03:32 UTC, randall-vx commented on cr_electronic_invoice/models/account_move.py
>                  #    inv.move_name = inv.invoice_id.display_name
same here

2020-12-02 03:33 UTC, randall-vx commented on cr_electronic_invoice_pos/models/electronic_invoice.py
>                          _logger.info('MAB - Email no enviado - cliente no definido')
Remove MBA from logger

2020-12-02 03:33 UTC, randall-vx requested changes
Request changes

2020-12-02 03:59 UTC, TheCloneMaster commented on cr_electronic_invoice_pos/models/electronic_invoice.py
>                          _logger.info('MAB - Email no enviado - cliente no definido')
Cómo cuesta quitar a ese MAB del camino....  ;-)
De una voy a reemplazar todos los k vea....

2020-12-02 04:23 UTC, ivanporras commented
@TheCloneMaster creo que esto va a tronar cuando tengas notas o secciones en la factura.

2020-12-03 04:11 UTC, TheCloneMaster commented
> @TheCloneMaster creo que esto va a tronar cuando tengas notas o secciones en la factura.

Habría que brincarse las líneas que no sean de ventas de productos... Tienes identificado cómo se distinguen?

2020-12-03 14:56 UTC, ivanporras commented
@TheCloneMaster creo que deberia ser asi
 if inv_line.product_id:
                            if inv_line.display_type not in ('line_section','line_note'):
                                line["codigo"] = inv_line.product_id.default_code or ''
                                line["codigoProducto"] = inv_line.product_id.code or ''
                                if inv_line.product_id.cabys_code:
                                    line["codigoCabys"] = inv_line.product_id.cabys_code
                                else:
                                    _no_CABYS_code='Aviso!.\nLinea sin código CABYS: %s' % inv_line.name
                                    continue
                        else:
                            #_no_CABYS_code='Aviso!.\nLinea sin código CABYS: %s' % inv_line.name
                            continue

2021-01-31 23:47 UTC, TheCloneMaster commented
> @TheCloneMaster creo que deberia ser asi
> if inv_line.product_id:
> if inv_line.display_type not in ('line_section','line_note'):
> line["codigo"] = inv_line.product_id.default_code or ''
> line["codigoProducto"] = inv_line.product_id.code or ''
> if inv_line.product_id.cabys_code:
> line["codigoCabys"] = inv_line.product_id.cabys_code
> else:
> _no_CABYS_code='Aviso!.\nLinea sin código CABYS: %s' % inv_line.name
> continue
> else:
> #_no_CABYS_code='Aviso!.\nLinea sin código CABYS: %s' % inv_line.name
> continue

Las líneas de sección o de notas no tienen product_id, pero sí hay k preguntar por ellas para ignorarlas más bien en el loop de invoice lines...
Ya apliqué el cambio, por favor lo revisan para ver si ya se puede aplicar el PR

2021-03-28 18:31 UTC, merged